### ISSUE TITLE
Plugin no longer works

### ISSUE THREAD

**Issue by technikhil314** [jonathanmorley/asdf-pnpm#10]
The registry.npmjs.org api seems to have changed. The list-all and instal or other commands are now working. 
Also the plugin does not follow new plugin format. 

I have created one here with latest template repo. https://github.com/technikhil314/asdf-pnpm

**Comment by joshlartz** [comment]
The plugin still works for me on pnpm v5, v6, and v7.

**Comment by technikhil314** [comment]
@joshlartz 

<img width="494" alt="Screenshot 2022-06-05 at 10 58 04 PM" src="https://user-images.githubusercontent.com/6815560/172062721-16b78c19-9e04-48dc-9d83-326d6b3e92eb.png">

**Comment by joshlartz** [comment]
@technikhil314 
```
> asdf plugin-list --urls | grep pnpm
pnpm                         https://github.com/jonathanmorley/asdf-pnpm.git
> asdf install pnpm $(asdf latest pnpm)
Downloading pnpm v7.1.8
> asdf local pnpm 7.1.8
> pnpm --version
7.1.8
```
