### ISSUE TITLE
`asdf reshim pnpm` does not prioritize over `nodejs`

### ISSUE THREAD

**Issue by scarf005** [jonathanmorley/asdf-pnpm#13]
```sh
$which pnpm
/home/scarf/.asdf/shims/pnpm
```

## /home/scarf/.asdf/shims/pnpm
```sh
#!/usr/bin/env bash
# asdf-plugin: nodejs 18.4.0
# asdf-plugin: pnpm 7.17.0
exec /home/scarf/.asdf/bin/asdf exec "pnpm" "$@" # asdf_allow: ' asdf '
```
```sh
 ~/r/S/frontend   main ±  cat ~/.tool-versions
nodejs 18.4.0
(...)
pnpm 7.17.0
```
both `asdf reshim pnpm` and `asdf reshim` doesn't reorder pnpm file, so i had to reorder them manually, like
```sh
#!/usr/bin/env bash
# asdf-plugin: pnpm 7.17.0
# asdf-plugin: nodejs 18.4.0
exec /home/scarf/.asdf/bin/asdf exec "pnpm" "$@" # asdf_allow: ' asdf '
```
would there be a solution to address such situation?

**Comment by jonathanmorley** [comment]
I don't think this is a responsibility of the pnpm plugin, but rather a bug with asdf.
I would advise not installing pnpm globally via npm, I assume that is what you did to get the nodejs line in the shim.
