### ISSUE TITLE
pnpm install -g not supported 

### ISSUE THREAD

**Issue by danielfalk** [jonathanmorley/asdf-pnpm#15]
**To Reproduce**

1. Run `asdf plugin install pnpm` 
2. Running `pnpm install -g <any global package>` gives the following error:

```
ERROR  Unable to find the global bin directory
Run "pnpm setup" to create it automatically, or set the global-bin-dir setting, or the PNPM_HOME env variable. The global bin directory should be in the PATH.
```

I think it's related to [this issue](https://github.com/pnpm/pnpm/issues/4658), which is that unlike npm, pnpm doesn't try to autodetect where to put the global installations.

And while you could configure it by running `pnpm setup`, then it would configure all asdf's pnpm installations to use the same directory, regardless of what version of pnpm you're using, which seems counter to asdf's purpose of allowing multiple versions being installed.

**Comment by jonathanmorley** [comment]
I'll defer this issue to see what approach pnpm takes upstream

**Comment by vanyauhalin** [comment]
@jonathanmorley, hi. Do you've any news on this issue?

**Comment by vanyauhalin** [comment]
@jonathanmorley 👀

**Comment by vanyauhalin** [comment]
@jonathanmorley Can we reopen this issue?
