### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by 1oglop1** [jonathanmorley/asdf-pnpm#16]
Hi, do you have time to maintain the plugin? because CI tests are failing because `ubuntu-16.04` was removed a long time ago and the same is also true for `18.04`. 

https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/

**Comment by jonathanmorley** [comment]
The time I have is low, but the maintenance on a repo this size is also quite low.
I have addressed the specific CI issue mentioned

**Comment by 1oglop1** [comment]
@jonathanmorley awesome, thank you :) 

In case you'd need more support for the maintenance of the project, you could transfer it under https://github.com/asdf-community

**Comment by bkaney** [comment]
Hi @jonathanmorley  / @1oglop1  -- I put in a PR in https://github.com/jonathanmorley/asdf-pnpm/pull/23 to allow the plugin to work in settings where npmjs is mirrors and not directly accessible (like corporate firewalls). It would be great to get 👀 on it! Thanks!
